version: '3.8'

services:
  backend:
    image: mi-api-hearthstone # El nombre que le diste al hacer 'docker build'
    container_name: hearthstone_backend
    env_file: 
      - .env
    ports:
      - "3001:3001"

  frontend:
    image: mi-front-hearthstone # El nombre que le diste al hacer 'docker build'
    container_name: hearthstone_frontend
    env_file: 
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend