version: '3.8'

services:
  # 1. Backend (Tu API REST en Node.js)
  backend:
    container_name: hearthstone_backend
    build: 
      context: ../Back  # Apunta a la carpeta Back
      dockerfile: Dockerfile
    env_file: 
      - ../.env # Inyecta las variables (las de Blizzard)
    ports:
      - "3001:3001" # Ajusta si tu backend usa otro puerto

  # 2. Frontend (Tu Deck Builder en Next.js)
  frontend:
    container_name: hearthstone_frontend
    build: 
      context: ../Front # Apunta a la carpeta Front
      dockerfile: Dockerfile
    env_file: 
      - ../.env
    ports:
      - "3000:3000"
    depends_on:
      - backend